@echo off
echo Starting Employee360 Backend...
cd /d "C:\Users\Gbs05262\HackathonWorkSpace\Employee360-dashboard\backend"
echo Installing backend dependencies...
pip install -r requirements.txt
echo Starting backend server...
python main.py
pause